apiVersion: apps/v1
kind: Deployment
metadata:
  name: mench-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: mench
  template:
    metadata:
      labels:
        app: mench
    spec:
      containers:
      - name: mench-container
        image: 1kasra/mench-app:latest
        ports:
        - containerPort: 5000
        readinessProbe:
          httpGet:
            path: /health
            port: 5000
          initialDelaySeconds: 3
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /health
            port: 5000
          initialDelaySeconds: 10
          periodSeconds: 30
